# -*- coding: utf-8 -*-
"""basketball_player_detection_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jrE2x7pS6e8bdB-ME3OJeuiH5orCiYk7
"""

# 安裝必要套件
!pip install -q ultralytics roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="qxXvlNarIRl13bYsGauo")
project = rf.workspace("workspace-5ujvu").project("basketball-players-fy4c2-vfsuv")
version = project.version(17)
dataset = version.download("yolov8")

# 印出 data.yaml 路徑確認
print("📂 Dataset 路徑：", dataset.location + "/data.yaml")

# 載入 YOLOv8x 模型並開始訓練
from ultralytics import YOLO

model = YOLO("yolov8x.pt")  # 使用 YOLOv8x，精度最高 ✅

model.train(
    data=f"{dataset.location}/data.yaml",  # 自動抓 Roboflow 資料集路徑
    epochs=200,
    imgsz=1280,  # 放大解析度，有助於偵測小目標（如球員手、頭等）
    batch=8,     # 如果 GPU 夠大可調高
    name="basketball_players_yolov8x"
)

import shutil
shutil.copy("runs/detect/basketball_players_yolov8x/weights/best.pt", "training_notebook/player_best.pt")