# -*- coding: utf-8 -*-
"""basketball_ball_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ipNs1E2-WH9yQRrOvhD0cihM0EQ6hvDy
"""
from roboflow import Roboflow
rf = Roboflow(api_key="qxXvlNarIRl13bYsGauo")
project = rf.workspace("workspace-5ujvu").project("basketball-players-fy4c2-vfsuv")
version = project.version(17)
dataset = version.download("yolov8")

# 印出 data.yaml 確認資料路徑
print("📂 Dataset 路徑：", dataset.location + "/data.yaml")

# 使用 YOLOv8x.pt 開始訓練
from ultralytics import YOLO

model = YOLO("yolov8x.pt")  # ✅ YOLOv8 精度最高版本

model.train(
    data=f"{dataset.location}/data.yaml",  # 使用 Roboflow 下載的正確路徑
    epochs=300,
    imgsz=1280,  # 放大輸入解析度幫助偵測小球
    batch=8,
    name="basketball_ball_yolov8x"
)

import shutil
shutil.copy("runs/detect/basketball_ball_yolov8x/weights/best.pt", "training_notebook/ball_best.pt")